name: Update Currency Rates

on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the script to update README.md
      run: python fetch_currencies.py

    - name: Commit and push changes
      run: |
        git config user.name "AmitavaDatta2004"
        git config user.email "dattaarup2004@gmail.com"
        git add README.md
        git commit -m "Automated update of exchange rates"
        git push
